### ISSUE TITLE
Circle timer animation

### ISSUE THREAD

**Issue by james-c-lars** [james-c-lars/cse110-w21-group11#20]
We want to add some extra visual appeal to our site through an animation which shows the progress of the timer. The idea proposed is a circle which winds down with the progress of the clock. We want the circle to be easily visible but without having an overwhelming presence.

**Comment by james-c-lars** [comment]
Brian finished the animation and is working to get it working with our own timer code in main

**Comment by lin-ister** [comment]
Finished
