### ISSUE TITLE
Max time of the pomo timer

### ISSUE THREAD

**Issue by james-c-lars** [james-c-lars/cse110-w21-group11#23]
Currently the timer won't allow a time greater than an hour and will perform a modulus operation on any time that the user enters. After discussion, we decided that we should allow the user to choose a timer from 0 minutes to 2 hours. We can display the amount of time remaining just in minutes and seconds, like 110 minutes 13 seconds. Fixing this will involve limiting what numbers the user can input for custom minutes in the settings menu, along with removing the modulus operation.

**Comment by arelae** [comment]
technically 120:59 is the max time user can input
